# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(319, 468)
        Form.setStyleSheet("")
        #self.setWindowFlag(Qt.FramelessWindowHint)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 320, 480))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("src/paisaje.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_IniciaSesion = QtWidgets.QLabel(self.frame)
        self.label_IniciaSesion.setGeometry(QtCore.QRect(28, 50, 270, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_IniciaSesion.setFont(font)
        self.label_IniciaSesion.setStyleSheet("\n"
"color:#fed4ff;\n"
"")
        self.label_IniciaSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_IniciaSesion.setObjectName("label_IniciaSesion")
        self.label_ = QtWidgets.QLabel(self.frame)
        self.label_.setGeometry(QtCore.QRect(0, 0, 320, 480))
        self.label_.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"")
        self.label_.setText("")
        self.label_.setObjectName("label_")
        self.lineEdit_user = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_user.setGeometry(QtCore.QRect(60, 150, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,250);\n"
"padding-bottom:7px;\n"
"padding-left:10px;\n"
"padding-right:10px;")
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_password.setGeometry(QtCore.QRect(60, 230, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(255,255,255,250);\n"
"padding-bottom:7px;\n"
"padding-left:10px;\n"
"padding-right:10px;")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_ingresar = QtWidgets.QPushButton(self.frame)
        self.pushButton_ingresar.setGeometry(QtCore.QRect(110, 330, 100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_ingresar.setFont(font)
        self.pushButton_ingresar.setStyleSheet("\n"
"QPushButton{\n"
"color:rgba(0,0,0,200);\n"
"background-color:rgba(138, 167, 255,200);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(0, 0, 255,200);\n"
"color:rgba(255,255,255,200);\n"
"}\n"
"")
        self.pushButton_ingresar.setObjectName("pushButton_ingresar")
        self.label_forgotpassword = QtWidgets.QLabel(self.frame)
        self.label_forgotpassword.setGeometry(QtCore.QRect(70, 380, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_forgotpassword.setFont(font)
        self.label_forgotpassword.setStyleSheet("color:rgba(255,255,255,140);")
        self.label_forgotpassword.setObjectName("label_forgotpassword")
        self.label_error = QtWidgets.QLabel(self.frame)
        self.label_error.setGeometry(QtCore.QRect(50, 282, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color:rgba(255, 251, 0,220);")
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.pushButton_cerrarlogin = QtWidgets.QPushButton(self.frame)
        self.pushButton_cerrarlogin.setGeometry(QtCore.QRect(300, 4, 15, 15))
        self.pushButton_cerrarlogin.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_cerrarlogin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/cerrar-login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_cerrarlogin.setIcon(icon)
        self.pushButton_cerrarlogin.setIconSize(QtCore.QSize(15, 15))
        self.pushButton_cerrarlogin.setObjectName("pushButton_cerrarlogin")
        self.label.raise_()
        self.label_.raise_()
        self.label_IniciaSesion.raise_()
        self.lineEdit_user.raise_()
        self.lineEdit_password.raise_()
        self.pushButton_ingresar.raise_()
        self.label_forgotpassword.raise_()
        self.label_error.raise_()
        self.pushButton_cerrarlogin.raise_()
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_IniciaSesion.setText(_translate("Form", "INICIO DE SESIÓN"))
        self.lineEdit_user.setPlaceholderText(_translate("Form", "Usuario"))
        self.lineEdit_password.setPlaceholderText(_translate("Form", "Contraseña"))
        self.pushButton_ingresar.setText(_translate("Form", "INGRESAR"))
        self.label_forgotpassword.setText(_translate("Form", "¿Olvidaste tu contraseña? Click aqui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
